
CASH_DEPOSIT = "واریز نقدی"
DEPOSIT_TO_OTHER_ACCOUNT = "واریز از حساب به حساب"
CASH_WITHDRAW = "برداشت نقدی"

WITHDRAW_ATM = "برداشت از خودپرداز"
DEPOSIT_TO_OTHER_ACCOUNT_ATM = "واریز از کارت به حساب"
DEPOSIT_TO_OTHER_CREDITCARD_ATM = "واریز از کارت به کارت"

BILL_PAYEMENT = "پرداخت قبض"
CHECK_PAYMNENT = "پرداخت چک"
LOAN_PAYMENT = "پرداخت وام"

types = [BILL_PAYEMENT, CASH_DEPOSIT, CASH_WITHDRAW, DEPOSIT_TO_OTHER_ACCOUNT, CHECK_PAYMNENT, LOAN_PAYMENT]



LOAN_PROFIT = 0.14/12
FA_BANK_ACCOUNT = 9432650726
BILL_USER_ACCOUNT = 13222
MAIN_BRANCH = 2782